### ISSUE TITLE
Chamilo wordpress

### ISSUE THREAD

**Issue by shabsshab** [chamilo/chamilo-wordpress#1]
In which version we can have the below features for wordpress chamilo pugin

a personal list of courses (not all the public ones but just yours)
a way to create accounts in Chamilo when they're created in Wordpress
a way to do Single Sign On (avoid double authentication in Wordpress and Chamilo)

**Comment by joserodriguez18** [comment]
> ¿En qué versión podemos tener las siguientes características para wordpress chamilo pugin?
> 
> una lista personal de cursos (no todos los públicos, sino solo los suyos)
> una forma de crear cuentas en Chamilo cuando se crean en Wordpress
> una forma de hacer Single Sign On (evitar la doble autenticación en Wordpress y Chamilo)

Podrían dar respuesta por favor

**Comment by ywarnier** [comment]
Hi, I don't maintain this plugin actively. It was developed as an example for a WordCamp.

From what I see in https://github.com/chamilo/chamilo-wordpress/blob/master/readme.txt it requires WordPress 4.3 or higher, and from the date (2016) it should be working with version 1.10 or 1.11 of Chamilo (all of the sub-versions of these two major versions too). See https://beeznest.com/blog/2011/09/27/history-of-chamilo-releases/ for a schedule of versions.

I am very open to Pull Requests if you use this plugin/module and find anything to improve (there is a lot to be improved).

**Comment by joserodriguez18** [comment]
Hola, comprendo eso, sin embargo tengo una duda.
Consumí la API SOAP y pude ingresar un nuevo usuario, lo que no he podido
hacer es traer la lista de cursos, no se qué parámetros mandarle a la
función como tal.
[image: image.png]
Tengo esto y no saca ni error ni muestra el curso, no sé que hacer la
verdad.
Si me puede explicar eso le agradecería grandemente.
Dios lo bendiga

**Comment by fabiowoj** [comment]
Hola, lo instalé en mi Wordpress 5.5.3 y el complemento funcionó, trayendo la lista completa por widget. Sin embargo, tendré que hacer alguna adaptación para crear el usuario en Chamilo cuando se cree en Wordpress. Para esto, estoy usando chamilo.php del complemento y agregando add_action ('user_register', 'chamilo_save_user', 20, 1); Creando la función chamilo_save_user en chamilo-functions.php.
Es solo el comienzo ... Espero haber ayudado.
